# Generated by Django 4.2.2 on 2024-08-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-update', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='updated',
            new_name='created',
        ),
        migrations.AddField(
            model_name='message',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
